[tool.black]
line-length = 76
target-version = ["py39"]
skip-string-normalization = true
preview = true            # новый алгоритм переносов

[tool.isort]
profile                    = "black"
line_length                = 76
multi_line_output          = 3      # vertical-hanging-indent
include_trailing_comma     = true
force_sort_within_sections = true
skip = ["venv", "migrations", "__pycache__"]

[tool.ruff]
line-length    = 76
target-version = "py39"

[tool.ruff.lint]           # новая вложенная секция
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort-совместимость
  "UP",  # pyupgrade
  "B",   # bugbear
  "C90", # mccabe (complexity)
]
ignore = [
  # docstrings
  "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
  # конфликт с Black
  "E203",
  # длиной строки управляет Black
  "E501",
]
exclude = [
  "tests", "*/migrations/*", "venv", "env", "data", "docs",
  "frontend", "infra", "__pycache__", "manage.py",
]
