[tool.black]
line-length = 76
target-version = ["py39"]
skip-string-normalization = true
preview = true

[tool.isort]
profile = "black"
line_length = 76
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
known_first_party = ["recipes", "users"]
skip = ["venv", "migrations", "__pycache__"]

[tool.ruff]
line-length = 76
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "C90"]
ignore = [
  "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
  "E203", "E501"
]
exclude = [
  "tests", "*/migrations/*", "venv", "env", "data", "docs",
  "frontend", "infra", "__pycache__", "manage.py"
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = ["recipes", "users"]
