name: Foodgram CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev python3-dev libjpeg-dev zlib1g-dev build-essential

      - name: Install backend dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Build frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps
          CI='' npm run build

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/foodgram_backend backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/foodgram_gateway frontend -f frontend/Dockerfile.prod

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/foodgram_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/foodgram_gateway

      - name: Copy docker-compose.production.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "infra/docker-compose.production.yml"
          target: "~/foodgram"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/foodgram
            docker-compose -f docker-compose.production.yml down
            docker-compose -f docker-compose.production.yml pull
            docker-compose -f docker-compose.production.yml up -d --force-recreate
            docker-compose -f docker-compose.production.yml exec -T foodgram_backend python manage.py migrate
            docker-compose -f docker-compose.production.yml exec -T foodgram_backend python manage.py collectstatic --noinput

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Foodgram: деплой завершён!
            👤 Автор: ${{ github.actor }}
            📃 Коммит: ${{ github.event.commits[0].message }}
            🔗 https://github.com/${{ github.repository }}/commit/${{ github.sha }}
